version: '3.4'

networks:
  cloud-services:
    external: true

services:
# file sharing service using Nextcloud
# broker 
  redis-nextcloud:
    image: redis:7.2.5
    container_name: redis-nextcloud
    environment:
      - TZ=${TIMEZONE}
    volumes:
      - ${VOLUMES_PATH}/cloud-services/nextcloud/redis:/data
    restart: unless-stopped
    networks:
      - cloud-services
  # database
  postgres-nextcloud:
    image: postgres:16.3
    container_name: postgres-nextcloud
    environment:
      - TZ=${TIMEZONE}
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    volumes:
      - ${VOLUMES_PATH}/cloud-services/nextcloud/pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - cloud-services
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user
    # app
  nextcloud:
    image: nextcloud:29.0.3
    container_name: nextcloud-app
    ports:
      - 8088:80
    environment:
      - POSTGRES_HOST=postgres-nextcloud
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - REDIS_HOST=redis-nextcloud
      - REDIS_PORT=6379
      #
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
      - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_admin_user
      - PHP_MEMORY_LIMIT=2G
      - PHP_UPLOAD_LIMIT=16G
       #
      - TRUSTED_PROXIES=${Nginx_Proxy}  #IP of nginx LXC in  proxmox
      - OVERWRITECLIURL=https://${Cloudflare_DNS}
      - OVERWRITEPROTOCOL=https
      - NEXTCLOUD_TRUSTED_DOMAINS=${Cloudflare_DNS}
      - OVERWRITEHOST=${Cloudflare_DNS}
      - NEXTCLOUD_DEFAULT_PHONE_REGION=RO
      #
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=465
      - SMTP_SECURE=STARTTLS
      - SMTP_AUTHTYPE=Login
      - SMTP_NAME=${SMT_name}
      - SMTP_PASSWORD=/run/secrets/smtp_password
      - MAIL_FROM_ADDRESS=nextcloud
      #- MAIL_DOMAIN=redacted.com
    volumes:
      - ${VOLUMES_PATH}/cloud-services/nextcloud/app/:/var/www/html
      - ${VOLUMES_PATH}/cloud-services/nextcloud/app/custom_apps:/var/www/html/custom_apps
      - ${VOLUMES_PATH}/cloud-services/nextcloud/app/config:/var/www/html/config
      - ${CLOUD_HDD_PATH}/nextcloud/data/:/var/www/html/data

    restart: unless-stopped
    networks:
      - cloud-services
    depends_on:
      - postgres-nextcloud
      - redis-nextcloud
    secrets:
      - nextcloud_admin_password
      - nextcloud_admin_user
      - postgres_db
      - postgres_password
      - postgres_user


secrets:
  nextcloud_admin_password:
    file: /docker-volumes/secrets/nextcloud_admin_password.txt # put admin password to this file
  nextcloud_admin_user:
    file: /docker-volumes/secrets/nextcloud_admin_user.txt # put admin username to this file
  postgres_db:
    file: /docker-volumes/secrets/postgres_db.txt # put postgresql db name to this file
  postgres_password:
    file: /docker-volumes/secrets/postgres_password.txt # put postgresql password to this file
  postgres_user:
    file: /docker-volumes/secrets/postgres_user.txt # put postgresql username to this file
  smtp_password:
    file: /docker-volumes/secrets/smtp_password.txt
